server:
  #端口号
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/itsystem?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper:
#  reasonable: false # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
#  support-methods-arguments: true
#  params: count=countSql
#  row-bounds-with-count: true
#  helper-dialect: mysql